// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqUl9qrdt-f45rgQLvPg1zTVQxy7M7MI',
    appId: '1:540198891235:web:580ed0aafcb6c87ada9fd6',
    messagingSenderId: '540198891235',
    projectId: 'expensesnap-783d7',
    authDomain: 'expensesnap-783d7.firebaseapp.com',
    storageBucket: 'expensesnap-783d7.firebasestorage.app',
    measurementId: 'G-J3887K71Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-9GLMmo8DbnfKP-70_fxm-WBptVSwwc',
    appId: '1:540198891235:android:cafbf38d1a6401cada9fd6',
    messagingSenderId: '540198891235',
    projectId: 'expensesnap-783d7',
    storageBucket: 'expensesnap-783d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMdV5pQadOwNcsiJJdahSbaORW7zjjmA',
    appId: '1:540198891235:ios:93bcea9dab71b3dcda9fd6',
    messagingSenderId: '540198891235',
    projectId: 'expensesnap-783d7',
    storageBucket: 'expensesnap-783d7.firebasestorage.app',
    iosBundleId: 'com.example.expenseSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqMdV5pQadOwNcsiJJdahSbaORW7zjjmA',
    appId: '1:540198891235:ios:93bcea9dab71b3dcda9fd6',
    messagingSenderId: '540198891235',
    projectId: 'expensesnap-783d7',
    storageBucket: 'expensesnap-783d7.firebasestorage.app',
    iosBundleId: 'com.example.expenseSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqUl9qrdt-f45rgQLvPg1zTVQxy7M7MI',
    appId: '1:540198891235:web:45be2231aec317c4da9fd6',
    messagingSenderId: '540198891235',
    projectId: 'expensesnap-783d7',
    authDomain: 'expensesnap-783d7.firebaseapp.com',
    storageBucket: 'expensesnap-783d7.firebasestorage.app',
    measurementId: 'G-J1TLP59LVM',
  );
}
